server:
  port: 8080

spring:
  config:
    import: configserver:http://config-server:8888
    cloud:
      config:
        uri: http://config-server:8888
        fail-fast: true
    application:
      name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceBreaker
                fallbackUri: forward:/fallback/user
        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: api-gateway