server:
  port: 8081

spring:
  application:
    name: user-service

  config:
    import: configserver:http://config-server:8888
    cloud:
      config:
        uri: http://config-server:8888
        fail-fast: true
    profiles:
      active: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: user-service

app:
  kafka:
    topic:
      user-events: user-events